objects/Example_A__c.object
<CustomObject>
    <label>Example_A</label>
    <nameField>
        <displayFormat>ExA-{0000}</displayFormat>
        <label>Example_A Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Example_As</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Example_B__c.object
<CustomObject>
    <fields>
        <fullName>Example_A__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Example_A</label>
        <referenceTo>Example_A__c</referenceTo>
        <relationshipLabel>Example_Bs</relationshipLabel>
        <relationshipName>Example_Bs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Example_B</label>
    <nameField>
        <displayFormat>ExB-{0000}</displayFormat>
        <label>Example_B Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Example_Bs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Example_C__c.object
<CustomObject>
    <fields>
        <fullName>Example_B__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Example_B</label>
        <referenceTo>Example_B__c</referenceTo>
        <relationshipLabel>Example_Cs</relationshipLabel>
        <relationshipName>Example_Cs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Example_C</label>
    <nameField>
        <displayFormat>ExC-{0000}</displayFormat>
        <label>Example_C Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Example_Cs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ExamplesController.cls
public class ExamplesController {

    @AuraEnabled
    public static List<wrappExample> fetchExamples(String recordId){
        Try{
   
			Map<String,WrappExample> mapWrappExample = new Map<String,WrappExample>();
            for(Example_B__c example_B : [SELECT Id,Name, Example_A__c FROM Example_B__c WHERE Example_A__c =: recordId ORDER BY Name]){
                WrappExample wrappExample = new WrappExample();
                wrappExample.idExample = example_B.id;
                wrappExample.nameExample = example_B.Name;
                wrappExample.Examples = new List<Object>();
				mapWrappExample.put(wrappExample.idExample,wrappExample);
             
            }
            
            if(!mapWrappExample.isEmpty()){
                for(Example_C__c example_C : [SELECT Id,Name, Example_B__c, Example_B__r.Name FROM Example_C__c WHERE Example_B__c =: mapWrappExample.keyset() ORDER BY Name]){
                    if(mapWrappExample.containsKey(example_C.Example_B__c)){ 
                      mapWrappExample.get(example_C.Example_B__c).Examples.add(example_C);    
                    }
                }
            }

            return mapWrappExample.values();
        }Catch(Exception e){
            throw new AuraHandledException(e.getMessage());
        }
    }
    
    
    public class WrappExample {
        @AuraEnabled public String idExample {get; set;}
        @AuraEnabled public String nameExample {get; set;}
        @AuraEnabled public List<Object> Examples {get; set;}
        
    }
    
}