objects/Example_A__c.object
<CustomObject>
    <label>Example_A</label>
    <nameField>
        <displayFormat>ExA-{0000}</displayFormat>
        <label>Example_A Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Example_As</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Example_B__c.object
<CustomObject>
    <fields>
        <fullName>Example_A__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Example_A</label>
        <referenceTo>Example_A__c</referenceTo>
        <relationshipLabel>Example_Bs</relationshipLabel>
        <relationshipName>Example_Bs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Example_B</label>
    <nameField>
        <displayFormat>ExB-{0000}</displayFormat>
        <label>Example_B Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Example_Bs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Example_C__c.object
<CustomObject>
    <fields>
        <fullName>Example_B__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Example_B</label>
        <referenceTo>Example_B__c</referenceTo>
        <relationshipLabel>Example_Cs</relationshipLabel>
        <relationshipName>Example_Cs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Example_C</label>
    <nameField>
        <displayFormat>ExC-{0000}</displayFormat>
        <label>Example_C Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Example_Cs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ExamplesControllerTest.cls
@isTest
public class ExamplesControllerTest {

    
    @TestSetup
    static void loadData(){
        Example_A__c example_A = new Example_A__c();
        insert example_A;
        
		List<Example_B__c> ltExample_B = new List<Example_B__c>();
		for(integer i = 0; i < 10; i++){
            Example_B__c example_B = new Example_B__c();
            example_B.Example_A__c = example_A.id;
            ltExample_B.add(example_B);
        }
        insert ltExample_B;
        
        List<Example_C__c> ltExample_c = new List<Example_C__c>();
        for(Example_B__c example_B: ltExample_B){
            Example_C__c example_C = new Example_C__c();
            example_C.Example_B__c = example_B.Id;
            ltExample_c.add(example_C);
        }
        
        insert ltExample_c;
        
    }
        
    @isTest
    static void success(){
        Example_A__c example_A = [SELECT ID FROM Example_A__c];
        
        Test.startTest();
        List<ExamplesController.wrappExample> fetchExamples = ExamplesController.fetchExamples(example_A.id);
        Test.stopTest();
        
		System.assertEquals(10, fetchExamples.size());

    }
    
	 @isTest
    static void error(){
        Example_A__c example_A = [SELECT ID FROM Example_A__c];
        
        Try{
        Test.startTest();
            List<ExamplesController.wrappExample> fetchExamples = ExamplesController.fetchExamples(null);
        Test.stopTest();
			System.assertEquals(0, fetchExamples.size());        
        }Catch(Exception e){
			System.assertEquals('Error', e.getMessage());
		}
    }



}